app:
    resource: "@AppBundle/Controller/"
    type:     annotation

lucky_number:
    path:       /lucky/number/{count}
    defaults:   {_controller: AppBundle:Lucky:number}

flickr:
    path:       /flickr/{startDate}/{endDate}
    defaults:   {_controller: AppBundle:Flickr:getPhoto}

